[package]
name = "inference-fattn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

description = "llama.cpp's FlashAttention kernels (fattn) for inference.rs."
repository.workspace = true
license.workspace = true

[dependencies]
candle-core.workspace = true
float8.workspace = true
half = { workspace = true }

[build-dependencies]
cudaforge = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
candle-nn.workspace = true

[features]
default = []
cuda = ["dep:cudaforge", "candle-core/cuda"]
