inference_metal_compile::metal_source_set! {
    pub const QUANT_METAL_SOURCE_SET;
    library_name: "inference_quant",
    source_dir: "kernels/metal",
    metal_sources: [
        "bitwise",
        "blockwise_fp8",
        "bnb_dequantize",
        "flash_attn",
        "fused_glu",
        "gguf_raw",
        "hqq_dequantize",
        "hqq_bitpack",
        "moe",
        "mxfp4",
        "quantized",
        "rotary",
        "rmsnorm_residual",
        "scalar_fp8",
        "sdpa_with_sinks",
        "softcap",
        "softmax_with_sinks",
        "topk_logits",
    ],
    header_sources: ["utils", "bf16"],
    include_only_sources: ["float8", "float4", "gguf_iq_tables"],
}
