[package]
name = "inference-layout"
readme = "../../README.md"
authors = ["Chris Thompson"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Document layout detection models for inference.rs."
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
inference-tensor.workspace = true
gemm = "0.19.0"
image.workspace = true
num_cpus = "1.17.0"
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
inference-kernel-build = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true

[features]
cuda = ["inference-tensor/cuda", "dep:inference-kernel-build"]
metal = ["inference-tensor/metal"]
