[package]
name = "inference-models-gemma"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
inference-tensor.workspace = true
image.workspace = true
inference-audio.workspace = true
inference-nn.workspace = true
inference-quant.workspace = true
inference-vision.workspace = true
itertools.workspace = true
rand.workspace = true
rand_distr.workspace = true
rand_isaac.workspace = true
regex.workspace = true
rubato.workspace = true
serde.workspace = true
serde_json.workspace = true
tokenizers.workspace = true
tracing.workspace = true

[dev-dependencies]
safetensors.workspace = true
tempfile.workspace = true

[features]
cuda = ["inference-tensor/cuda", "inference-quant/cuda", "inference-nn/cuda"]
metal = ["inference-tensor/metal", "inference-quant/metal", "inference-nn/metal"]
