[package]
name = "inference-models-diffusion"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
inference-tensor.workspace = true
inference-nn.workspace = true
inference-quant.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_plain.workspace = true
tokenizers.workspace = true
tracing.workspace = true

[features]
cuda = ["inference-tensor/cuda", "inference-quant/cuda", "inference-nn/cuda"]
metal = ["inference-tensor/metal", "inference-quant/metal", "inference-nn/metal"]
