[package]
name = "inference-nn"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
akin.workspace = true
anyhow.workspace = true
inference-tensor.workspace = true
inference-flash-attn-v3 = { workspace = true, optional = true }
csv.workspace = true
either.workspace = true
float8.workspace = true
half.workspace = true
image.workspace = true
indexmap.workspace = true
indicatif.workspace = true
inference-audio.workspace = true
inference-fattn = { workspace = true, optional = true }
inference-paged-attn = { workspace = true, optional = true }
inference-quant.workspace = true
itertools.workspace = true
metrics.workspace = true
num-traits.workspace = true
rand.workspace = true
rand_isaac.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokenizers = { workspace = true, features = ["fancy-regex"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "ios", target_os = "tvos"))'.dependencies]
objc2-metal = { workspace = true, optional = true }
candle-metal-kernels = { workspace = true, optional = true }

[build-dependencies]
cudaforge = { workspace = true, optional = true }

[features]
utoipa = ["dep:utoipa"]
cuda = [
    "inference-tensor/cuda",
    "dep:cudaforge",
    "inference-quant/cuda",
    "dep:inference-paged-attn",
    "inference-paged-attn/cuda",
    "dep:inference-fattn",
    "inference-fattn/cuda",
]
cutile = ["cuda", "inference-quant/cutile"]
metal = [
    "inference-tensor/metal",
    "inference-quant/metal",
    "dep:candle-metal-kernels",
    "dep:inference-paged-attn",
    "inference-paged-attn/metal",
    "dep:objc2-metal"
]
flash-attn-v3 = ["cuda", "dep:inference-flash-attn-v3"]
accelerate = ["inference-tensor/accelerate", "inference-quant/accelerate"]
