[package]
name = "inference-models-speech"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
inference-tensor.workspace = true
inference-nn.workspace = true
inference-quant.workspace = true
rand.workspace = true
rayon.workspace = true
unicode-normalization.workspace = true
vernacula-phonemizer = { git = "https://github.com/christopherthompson81/vernacula-phonemizer", rev = "8211aacf" }
rand_distr.workspace = true
rand_isaac.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[features]
cuda = ["inference-tensor/cuda", "inference-quant/cuda", "inference-nn/cuda"]
metal = ["inference-tensor/metal", "inference-quant/metal", "inference-nn/metal"]

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
